logging:
  level:
    root: WARN

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  datasource:
    url: jdbc:hsqldb:hsql://localhost/overrides
  main:
    banner-mode: 'off'
