logging:
  level:
    root: WARN

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  datasource:
    url: jdbc:hsqldb:file:./target/overrides;create=true;shutdown=true
  main:
    banner-mode: 'off'
