CREATE TABLE OVERRIDES.p_Example_overrides (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  example_id INTEGER UNIQUE FOREIGN KEY REFERENCES OVERRIDES.p_Examples(id),
  name VARCHAR(99) NOT NULL
);
